### ISSUE TITLE
View http sessions appear "None"

### ISSUE THREAD

**Issue by bientt210** [javamelody/sonar-javamelody#5]
I'm install plugin for sonar version 1.81.0 but in part "View http sessions" not appear any information, can someone explain why was that?
Thank you in advance.

<img width="813" alt="Screen Shot 2020-01-17 at 09 46 36" src="https://user-images.githubusercontent.com/47659964/72580673-63360a00-390f-11ea-8bd3-793aac86294a.png">

**Comment by evernat** [comment]
That's normal.
Since Sonarqube 6.1, Sonarqube's authentication was changed and does not create an http session. In fact, http sessions are never created in Sonarqube. To be sure of that, Sonarqube throws `UnsupportedOperationException: Sessions are disabled so that web server is stateless` if some code tries to create an http session.

So javamelody says that there are no http sessions in Sonarqube, because there are really never http sessions in Sonarqube.
